export { default as binaneLogo } from './binance_logo.svg';
export { default as bitcoinLogo } from './bitcoin_logo.svg';
export { default as etheriumLogo } from './etherium_logo.svg';
export { default as fbLogo } from './facebook_logo.svg';
export { default as linkedInLogo } from './linkedin_logo.svg';
export { default as solanaLogo } from './solana-sol-logo.svg';
export { default as tetherLogo } from './tether_logo.svg';
export { default as twitterLogo } from './twitter_logo.svg';
export { default as xrpLogo } from './xrp_logo.svg';
